### ISSUE TITLE
string saved on int ref

### ISSUE THREAD

**Issue by caburj** [ValdemarGr/rescript-post#1]
https://github.com/ValdemarGr/rescript-post/blob/b0e837c97d5094823a00288f5abd2d68695e68c9/src/Refactored/Entry.res#L25

Is it normal that the compiler allows this? Inputting new will will just concatenate the items' contents because the new value is a string.

**Comment by ValdemarGr** [comment]
The browser API is unfortunately a bit untyped so `target(x)["value"]` has any type (`{..}`).

You're right that the input should be parsed before mutating the state.

## Update
Fixed
